<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Payment Receipt #{{ $payment->id }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #18181b;
            line-height: 1.6;
            margin: 0;
            padding: 40px;
        }
        .header {
            border-bottom: 2px solid #18181b;
            padding-bottom: 20px;
            margin-bottom: 40px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .brand {
            font-size: 24px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 2px;
        }
        .receipt-label {
            font-size: 10px;
            text-transform: uppercase;
            letter-spacing: 4px;
            color: #71717a;
            margin-top: 5px;
        }
        .details-grid {
            width: 100%;
            margin-bottom: 60px;
        }
        .details-grid td {
            vertical-align: top;
            width: 50%;
        }
        .section-title {
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 2px;
            color: #a1a1aa;
            margin-bottom: 10px;
        }
        .info-value {
            font-size: 14px;
            font-weight: bold;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 40px;
        }
        .table th {
            text-align: left;
            font-size: 10px;
            text-transform: uppercase;
            letter-spacing: 2px;
            color: #71717a;
            padding: 12px 0;
            border-bottom: 1px solid #e4e4e7;
        }
        .table td {
            padding: 20px 0;
            border-bottom: 1px solid #f4f4f5;
        }
        .amount-row td {
            font-size: 18px;
            font-weight: bold;
        }
        .footer {
            margin-top: 100px;
            font-size: 10px;
            color: #a1a1aa;
            text-align: center;
            text-transform: uppercase;
            letter-spacing: 2px;
        }
        .status-badge {
            display: inline-block;
            padding: 4px 12px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
            background: #f0fdf4;
            color: #166534;
            border: 1px solid #dcfce7;
        }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="brand">IronCoach</div>
            <div class="receipt-label">Official Fiscal Receipt</div>
        </div>
    </div>

    <table class="details-grid">
        <tr>
            <td>
                <div class="section-title">Billed To</div>
                <div class="info-value">{{ $payment->client->user->name }}</div>
                <div class="info-value" style="font-weight: normal; color: #71717a;">{{ $payment->client->user->email }}</div>
            </td>
            <td style="text-align: right;">
                <div class="section-title">Transaction Details</div>
                <div class="info-value">#{{ $payment->id }}</div>
                <div class="info-value" style="font-weight: normal; color: #71717a;">Date: {{ $payment->date }}</div>
                <div style="margin-top: 10px;">
                    <span class="status-badge">{{ $payment->status }}</span>
                </div>
            </td>
        </tr>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th>Service Description</th>
                <th style="text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <div style="font-weight: bold;">Coaching & Nutrition Protocol Sync</div>
                    <div style="font-size: 11px; color: #71717a; margin-top: 4px;">Professional guidance and program management services.</div>
                </td>
                <td style="text-align: right; font-weight: bold;">{{ number_format($payment->amount, 2) }} MAD</td>
            </tr>
            <tr class="amount-row">
                <td style="text-align: right; padding-right: 20px;">Total Amount Paid</td>
                <td style="text-align: right; color: #0891b2;">{{ number_format($payment->amount, 2) }} MAD</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Generated by IronCoach Digital Management System // {{ now()->toDateTimeString() }}
    </div>
</body>
</html>
