@startuml
left to right direction
skinparam packageStyle rectangle

actor "Coach (Achraf)" as Coach

rectangle "Sprint 1: Gestion des Ressources" {
  
  package "Gestion des Clients" {
    (Ajouter un Client) as (AddC)
    (Modifier un Client) as (EditC)
    (Supprimer un Client) as (DelC)
    (Afficher la liste des Clients) as (ListC)
  }
  
  package "Structure Alimentaire" {
    (Gérer les Catégories) as (Cat)
    (Créer un Repas) as (AddM)
    (Saisir Description & Macros) as (Macro)
    
    (AddM) ..> (Macro) : <<include>>
    (AddM) ..> (Cat) : <<uses>>
  }

  Coach -- (AddC)
  Coach -- (EditC)
  Coach -- (DelC)
  Coach -- (ListC)
  
  Coach -- (Cat)
  Coach -- (AddM)
}
@enduml
