@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Coach (Achraf)" as Coach
actor "Application Mobile" as MobileApp

rectangle "Sprint 1: Gestion des Ressources" {
  
  package "Gestion des Clients" {
    (Ajouter un Client) as (AddC)
    (Modifier un Client) as (EditC)
    (Supprimer un Client) as (DelC)
    (Afficher la liste des Clients) as (ListC)
  }
  
  package "Structure Alimentaire" {
    (Gérer les Catégories) as (Cat)
    (Créer un Repas) as (AddM)
    (Saisir Macros-nutriments) as (Macro)
    
    (AddM) ..> (Macro) : <<include>>
    (AddM) ..> (Cat) : <<include>>
  }

  package "API Rest (Mobile)" {
    (Consommer les Ressources) as (ConsumeAPI)
  }

  Coach -- (AddC)
  Coach -- (EditC)
  Coach -- (DelC)
  Coach -- (ListC)
  Coach -- (Cat)
  Coach -- (AddM)
  
  MobileApp -- (ConsumeAPI)
}
@enduml